#!/usr/bin/env python3
"""
check_asset_anonymization.py — submission-stage asset/peripheral anonymization gate.

Body-text anonymization is mature; the blind spot is *peripheral artifacts*. A
double-anonymized submission was nearly broken because a flow-diagram figure,
generated by a script with a hardcoded institution label, carried the real
hospital name — invisible to any docx text scan. File metadata (docx
`dc:creator`, PDF `/Author`) is a second blind spot.

This detector scans a submission/project directory for three deterministic
classes of leak:

  1. **figure-script hardcoded institution** — a figure-generating script
     (`figures/**/*.R|*.py`, or any `*.R|*.py` under a `figures*` dir) contains
     an institution-like token (Hospital / University / Medical Center / IRB /
     병원 / 의료원 …) or a name supplied via --names-file.
  2. **figure/asset PDF rendered text** — a figure PDF's extracted text carries
     an institution token or a --names-file name (de-anonymization risk). When a
     figure carries *any* rendered text, a `visual_check` advisory is emitted
     (text scanning cannot see rasterized labels).
  3. **document metadata author** — a `.docx` `dc:creator`/`cp:lastModifiedBy`
     or a `.pdf` Author/Creator is a real person/identifier (not empty / not a
     known tool).
  4. **docx embedded absolute path** — a `word/*.xml` attribute (e.g. a drawing's
     `<pic:cNvPr descr="...">`) carries an absolute home-dir path
     (`/Users/<user>/…`, `/home/<user>/…`). pandoc writes the source image path
     into the picture description when handed an absolute path, leaking the
     username into the docx body XML where a rendered-text scan never sees it.
     Fix: use a relative image path + `pandoc --resource-path=<figdir>`.

Severity:
  - `leak`   — metadata author present, or a --names-file name found anywhere.
  - `review` — institution-token hit, or a figure carries rendered text.

Exit: 0 = clean, 1 = findings (any `leak`; also `review` under --strict),
2 = usage/error. Degrades gracefully when poppler (pdftotext/pdfinfo) is absent:
script-grep and docx-metadata checks still run; PDF text/metadata checks are
reported as skipped (poppler_available:false) rather than silently passing.

Patterns are generic — no real names are baked in. Supply institution/author
names locally with --names-file (one per line); that file is never committed.

Stdlib-only.

Usage:
    python3 check_asset_anonymization.py --dir submission/ [--names-file names.txt]
        [--out qc/asset_anon.json] [--strict] [--quiet]
"""

from __future__ import annotations

import argparse
import json
import re
import shutil
import subprocess
import sys
import zipfile
from dataclasses import dataclass, field, asdict
from pathlib import Path

# Generic institution / ethics-board tokens (English + Korean). No proper names.
INSTITUTION_RE = re.compile(
    r"\b(?:Hospital|Hospitals|University|Universit[äe]t|College of Medicine|"
    r"School of Medicine|Faculty of Medicine|Medical Cent(?:er|re)|Health System|"
    r"Cancer Cent(?:er|re)|Infirmary|Institutional Review Board|"
    r"IRB(?:[\s.:#-]*(?:No|Number|#)|\s*approval)?)\b"
    r"|병원|의료원|의과대학|대학교|연구윤리",
    re.IGNORECASE,
)

# docx/pdf metadata authorship values that are NOT a real person (tools/blanks).
TOOL_AUTHORS = (
    "unknown", "microsoft office user", "pandoc", "libreoffice", "writer",
    "openoffice", "word", "microsoft word", "google", "overleaf", "latex",
    "pdftex", "pdflatex", "xelatex", "lualatex", "quarto", "rmarkdown",
    "knitr", "wps", "author",
)


def _is_tool_author(value: str) -> bool:
    """True if a metadata author value is blank or a known tool (not a person)."""
    v = value.strip().lower()
    if not v:
        return True
    return any(v == t or v.startswith(t) for t in TOOL_AUTHORS)

FIG_SCRIPT_GLOBS = ("*.R", "*.r", "*.py")
DC_CREATOR_RE = re.compile(r"<dc:creator>([^<]*)</dc:creator>")
LAST_MOD_RE = re.compile(r"<cp:lastModifiedBy>([^<]*)</cp:lastModifiedBy>")
# Absolute home-dir path leaked into an OOXML attribute (e.g. a drawing's
# <pic:cNvPr descr="/Users/<user>/.../fig.png">). pandoc embeds the source image
# path as the picture description when given an absolute path; it carries the
# username into the docx body XML, invisible to a rendered-text scan.
DOCX_ABS_PATH_RE = re.compile(r'(?:descr|name|title)="(/(?:Users|home)/[^"]+)"')


@dataclass
class Finding:
    type: str
    severity: str  # "leak" | "review"
    path: str
    detail: str


@dataclass
class Report:
    findings: list[Finding] = field(default_factory=list)
    scanned: dict[str, int] = field(default_factory=dict)
    poppler_available: bool = False
    skipped: list[str] = field(default_factory=list)

    @property
    def has_leak(self) -> bool:
        return any(f.severity == "leak" for f in self.findings)

    def submission_safe(self, strict: bool) -> bool:
        if self.has_leak:
            return False
        if strict and any(f.severity == "review" for f in self.findings):
            return False
        return True

    def as_dict(self, strict: bool) -> dict:
        return {
            "submission_safe": self.submission_safe(strict),
            "strict": strict,
            "poppler_available": self.poppler_available,
            "scanned": self.scanned,
            "skipped": self.skipped,
            "summary": {
                "leak": sum(1 for f in self.findings if f.severity == "leak"),
                "review": sum(1 for f in self.findings if f.severity == "review"),
            },
            "findings": [asdict(f) for f in self.findings],
        }


def _is_under_figures(p: Path) -> bool:
    return any(part.lower().startswith(("figure", "fig", "graphic")) for part in p.parts)


def _load_names(names_file: Path | None) -> list[str]:
    if not names_file:
        return []
    out = []
    for line in names_file.read_text(encoding="utf-8", errors="replace").splitlines():
        s = line.strip()
        if s and not s.startswith("#"):
            out.append(s)
    return out


def _name_hits(text: str, names: list[str]) -> list[str]:
    low = text.lower()
    return [n for n in names if n.lower() in low]


def _pdftotext(pdf: Path) -> str | None:
    try:
        r = subprocess.run(["pdftotext", "-q", str(pdf), "-"],
                           capture_output=True, text=True, timeout=60)
        return r.stdout
    except Exception:
        return None


def _pdf_author(pdf: Path) -> str | None:
    try:
        r = subprocess.run(["pdfinfo", str(pdf)], capture_output=True, text=True, timeout=30)
    except Exception:
        return None
    author = creator = ""
    for line in r.stdout.splitlines():
        if line.startswith("Author:"):
            author = line.split(":", 1)[1].strip()
        elif line.startswith("Creator:"):
            creator = line.split(":", 1)[1].strip()
    for v in (author, creator):
        if v and not _is_tool_author(v):
            return v
    return None


def _docx_authors(docx: Path) -> list[str]:
    try:
        with zipfile.ZipFile(docx) as z:
            if "docProps/core.xml" not in z.namelist():
                return []
            core = z.read("docProps/core.xml").decode("utf-8", errors="replace")
    except Exception:
        return []
    vals = []
    for m in (*DC_CREATOR_RE.finditer(core), *LAST_MOD_RE.finditer(core)):
        v = m.group(1).strip()
        if v and not _is_tool_author(v):
            vals.append(v)
    return vals


def _docx_embedded_abs_paths(docx: Path) -> list[str]:
    """Absolute home-dir paths leaked into word/*.xml attributes (e.g. a
    pandoc-embedded image's pic descr). Returns the offending path strings."""
    hits: list[str] = []
    try:
        with zipfile.ZipFile(docx) as z:
            parts = [n for n in z.namelist()
                     if n.startswith("word/") and n.endswith(".xml")]
            for name in parts:
                xml = z.read(name).decode("utf-8", errors="replace")
                for m in DOCX_ABS_PATH_RE.finditer(xml):
                    hits.append(m.group(1))
    except Exception:
        return []
    # de-dup, preserve order
    seen: set[str] = set()
    out = []
    for h in hits:
        if h not in seen:
            seen.add(h)
            out.append(h)
    return out


def build_report(root: Path, names: list[str], poppler: bool) -> Report:
    rep = Report(poppler_available=poppler)
    scripts = docx_files = pdf_files = 0

    for p in sorted(root.rglob("*")):
        if not p.is_file() or "__pycache__" in p.parts:
            continue
        suffix = p.suffix.lower()
        rel = str(p.relative_to(root))

        # 1. figure-generating scripts AND the config files that drive them.
        #
        # A figure builder does not have to be a script. `/make-figures` documents its STROBE
        # builder as `build_strobe_template.py --config figures/figure1_strobe.yaml`, and the first
        # box of a STROBE flow diagram is exactly where "Patients screened at <Hospital>" lives.
        # Scanning only .r/.py meant the identical institution string blocked in one file and
        # passed in the other:
        #
        #   figures/figure1_strobe.py    -> FAIL: institution-like token in figure script
        #   figures/figure1_strobe.yaml  -> PASS: no anonymization leak  ({'figure_scripts': 0})
        #
        # For a double-blind submission that is an anonymity leak which the anonymisation gate
        # declared clean. The builders in this repo parse YAML and JSON alike, so both are now read
        # the way the scripts already were — as text, line by line, which is all this check needs.
        if suffix in (".r", ".py", ".yaml", ".yml", ".json") and _is_under_figures(p):
            scripts += 1
            text = p.read_text(encoding="utf-8", errors="replace")
            for i, line in enumerate(text.splitlines(), 1):
                if INSTITUTION_RE.search(line):
                    rep.findings.append(Finding(
                        "figure_script_institution", "review", f"{rel}:{i}",
                        f"institution-like token in figure script: {line.strip()[:120]}"))
                for n in _name_hits(line, names):
                    rep.findings.append(Finding(
                        "figure_script_name", "leak", f"{rel}:{i}",
                        f"name '{n}' hardcoded in figure script"))

        # 2 + 3. docx metadata
        elif suffix == ".docx":
            docx_files += 1
            for a in _docx_authors(p):
                rep.findings.append(Finding(
                    "docx_metadata_author", "leak", rel,
                    f"docx author metadata: '{a}'"))
            # 4. absolute home-dir path embedded in word/*.xml (e.g. pic descr)
            for ap_ in _docx_embedded_abs_paths(p):
                rep.findings.append(Finding(
                    "docx_embedded_abs_path", "leak", rel,
                    f"absolute path in docx XML (username leak; use a relative "
                    f"image path + pandoc --resource-path): {ap_}"))

        # PDFs: metadata + (figure) rendered-text
        elif suffix == ".pdf":
            pdf_files += 1
            if poppler:
                a = _pdf_author(p)
                if a:
                    rep.findings.append(Finding(
                        "pdf_metadata_author", "leak", rel, f"pdf author/creator: '{a}'"))
                if _is_under_figures(p):
                    txt = _pdftotext(p)
                    if txt is None:
                        rep.skipped.append(f"pdftotext failed: {rel}")
                    elif txt.strip():
                        rep.findings.append(Finding(
                            "figure_rendered_text", "review", rel,
                            "figure PDF carries rendered text — visual-check for "
                            "institution/IRB#/author labels a text scan cannot see"))
                        if INSTITUTION_RE.search(txt):
                            rep.findings.append(Finding(
                                "figure_text_institution", "review", rel,
                                "institution-like token in figure PDF text"))
                        for n in _name_hits(txt, names):
                            rep.findings.append(Finding(
                                "figure_text_name", "leak", rel,
                                f"name '{n}' in figure PDF text"))
            else:
                rep.skipped.append(f"poppler unavailable, PDF not scanned: {rel}")

    rep.scanned = {"figure_scripts": scripts, "docx": docx_files, "pdf": pdf_files}
    return rep


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(
        description="Submission-stage asset/figure/metadata anonymization gate.")
    ap.add_argument("--dir", type=Path, default=Path.cwd(),
                    help="Root directory to scan (default: cwd).")
    ap.add_argument("--names-file", type=Path, default=None,
                    help="Newline-separated institution/author names to flag (local only).")
    ap.add_argument("--out", type=Path, default=None, help="Write JSON report here.")
    ap.add_argument("--strict", action="store_true",
                    help="Also fail on 'review' findings (institution tokens, rendered text).")
    ap.add_argument("--quiet", action="store_true", help="Suppress stdout summary.")
    args = ap.parse_args(argv)

    if not args.dir.is_dir():
        print(f"ERROR: --dir not a directory: {args.dir}", file=sys.stderr)
        return 2
    if args.names_file is not None and not args.names_file.is_file():
        print(f"ERROR: --names-file not a file: {args.names_file}", file=sys.stderr)
        return 2

    poppler = shutil.which("pdftotext") is not None and shutil.which("pdfinfo") is not None
    names = _load_names(args.names_file)
    rep = build_report(args.dir, names, poppler)
    safe = rep.submission_safe(args.strict)

    if args.out is not None:
        args.out.parent.mkdir(parents=True, exist_ok=True)
        args.out.write_text(json.dumps({"detector": "check_asset_anonymization", **rep.as_dict(args.strict)}, indent=2), encoding="utf-8")

    if not args.quiet:
        if not poppler:
            print("NOTE: poppler (pdftotext/pdfinfo) not found — PDF text/metadata "
                  "checks skipped; install poppler-utils for full coverage.")
        if safe:
            n = len(rep.findings)
            print(f"PASS: no anonymization leak ({rep.scanned}; {n} advisory finding(s)).")
        else:
            print(f"FAIL: anonymization findings — {rep.as_dict(args.strict)['summary']}")
            for f in rep.findings:
                print(f"  - [{f.severity}] {f.type} {f.path}: {f.detail}")

    return 0 if safe else 1


if __name__ == "__main__":
    sys.exit(main())
