#!/usr/bin/env python3
"""Every image we ship must be one we are allowed to ship.

This repository is **MIT-licensed** and it is distributed — on npm, and as a classroom ZIP that every
user downloads. MIT tells the world it may "use, copy, modify, merge, publish, distribute,
sublicense, and sell" what is inside. That is a promise about *our* rights, and we can only make it
about material we actually hold.

On 2026-07-14 we found ten PNGs under `skills/make-figures/references/exemplar_diagrams/` that had
been **cropped from published papers**. The directory's own README said so, and promised each came
with a sidecar recording "source PDF, page, DOI, crop coords" — and that the sidecar "records DOI and
source for every exemplar."

It recorded `label`, `figure_type`, `dpi`. No source, no DOI, no licence. Eight of the eighteen
images had no sidecar at all. The safeguard the README described had never been written, and nothing
checked. The README also argued fair use on the grounds that exemplars are "not redistributed as part
of generated figures" — true, and beside the point: they were redistributed as part of the *package*.

**A figure you may legally read is not a figure you may legally ship.**

So: every raster image under `skills/` (the payload) must either be

  * **ours** — generated by a script in this repository, listed in SELF_GENERATED below; or
  * **licensed for redistribution** — accompanied by a `<name>.meta.yaml` declaring `source` and a
    `license` that permits it (CC-BY, CC0, public domain, or an explicit own-work marker).

An image with neither fails the build. There is no "probably fine" tier, because the whole failure
was a "probably fine" that nobody had checked.

## The images that hide inside containers

A `.pptx` is a zip. So is a `.docx`. The first version of this gate globbed the filesystem, and on
the filesystem a container is one opaque binary — so it walked straight past nine images, 236 KB,
riding inside `european_radiology.pptx`: the European Society of Radiology's logo and wordmark, and
a four-panel labelled patient CT figure belonging to a published article (`docProps/app.xml` still
named the paper). The gate written to stop exactly this printed **"OK: all 8 bundled image(s) may
be shipped"** and exited 0.

That is the same defect as the one it exists to catch, one layer down: a check that runs, passes,
and is looking in the wrong place. So it now opens every OOXML container and holds the images
inside to the same standard as the images beside it. An image is shipped whether or not it is
wrapped in a zip.

Usage:
    check_bundled_media_license.py [--strict]

Stdlib only.
"""

from __future__ import annotations

import argparse
import re
import sys
import zipfile
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SKILLS = ROOT / "skills"

RASTER = {".png", ".jpg", ".jpeg", ".gif", ".webp", ".tif", ".tiff", ".bmp"}

# OOXML: a zip wearing a document's extension. Its media entries ship as surely as a loose .png —
# more quietly, which is the whole problem.
CONTAINER = {".pptx", ".docx", ".xlsx"}

# The payload is `ppt/media/` — the images someone put IN the document.
#
# `docProps/thumbnail.jpeg` is not payload. PowerPoint renders it from the deck's own slides every
# time you save, so it can never contain anything the deck does not already contain, and it is
# present in every file python-pptx writes. Counting it would fire this gate on a contributor's
# brand-new, entirely original template — and a gate that fires on good work gets switched off, and
# takes the honest gates with it. (The European Radiology file failed on its SEVEN `ppt/media`
# images. It did not need its thumbnail to convict it.)
IN_CONTAINER_MEDIA = re.compile(r"(^|/)(ppt|word|xl)/media/", re.IGNORECASE)

# Images this project renders itself. Each entry is a filename glob plus the script that makes it —
# named, so that "it is ours" is a claim someone wrote down rather than an assumption.
SELF_GENERATED = {
    "template_output*.png": "skills/make-figures/scripts/generate_flow_diagram.R",
}

# A container someone ELSE made that carries images, and which we are nonetheless entitled to
# redistribute. The value is the evidence — the licence, and where it is stated — not a shrug.
#
# "It is the official template, surely that is fine" is not permission. It is the sentence that
# shipped a patient's CT scan: the European Radiology template we used to carry was the journal's
# own file with a published paper's graphical abstract still filled into slide 2 — the ESR wordmark
# and that paper's four-panel CT figure, seven images, inside an MIT package anyone may sell. It
# carried no licence, and this gate could not see it, because a .pptx is a zip. It was removed.
# Users who want the journal's template download it and pass `--template /absolute/path.pptx`, which
# the generator has always accepted.
THIRD_PARTY_CONTAINERS = {
    "skills/make-figures/templates/official/stard2015/STARD_2015_checklist.docx":
        "CC BY 4.0 — Bossuyt PM et al., BMJ 2015;351:h5527 (equator-network.org)",
}

# Licences that permit redistribution inside an MIT-licensed package.
OK_LICENSES = re.compile(
    r"\b(cc0|cc-?by(-sa)?(-\d\.\d)?|public[- ]domain|own[- ]work|mit|apache|bsd)\b",
    re.IGNORECASE,
)


def self_generated(p: Path) -> bool:
    return any(p.match(g) for g in SELF_GENERATED)


def sidecar_ok(p: Path) -> tuple[bool, str]:
    meta = p.with_suffix("").with_suffix(".meta.yaml")
    if not meta.exists():
        meta = p.parent / (p.stem + ".meta.yaml")
    if not meta.exists():
        return False, "no <name>.meta.yaml beside it"

    text = meta.read_text(encoding="utf-8", errors="ignore")
    has_source = re.search(r"^\s*(source|doi|url)\s*:\s*\S", text, re.MULTILINE)
    lic = re.search(r"^\s*licen[sc]e\s*:\s*(.+)$", text, re.MULTILINE)

    if not has_source:
        return False, "meta.yaml declares no source / doi / url"
    if not lic:
        return False, "meta.yaml declares no license"
    if not OK_LICENSES.search(lic.group(1)):
        return False, f"license {lic.group(1).strip()!r} does not clearly permit redistribution"
    return True, ""


def embedded_media(container: Path) -> list[tuple[str, int]]:
    """Every raster riding inside an OOXML zip. (name, bytes)"""
    out: list[tuple[str, int]] = []
    try:
        with zipfile.ZipFile(container) as z:
            for info in z.infolist():
                if info.is_dir():
                    continue
                suffix = Path(info.filename).suffix.lower()
                if suffix in RASTER and IN_CONTAINER_MEDIA.search(info.filename):
                    out.append((info.filename, info.file_size))
    except zipfile.BadZipFile:
        return []
    return sorted(out)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--strict", action="store_true", help="exit 1 on any image we cannot ship")
    ap.add_argument("--root", type=Path, default=ROOT,
                    help="tree to inspect (the self-test points this at a fixture)")
    a = ap.parse_args()

    root = a.root.resolve()
    skills_dir = root / "skills"

    images = sorted(p for p in skills_dir.rglob("*") if p.suffix.lower() in RASTER and p.is_file())
    bad: list[tuple[Path, str]] = []
    ours = 0
    licensed = 0

    for p in images:
        if self_generated(p):
            ours += 1
            continue
        ok, why = sidecar_ok(p)
        if ok:
            licensed += 1
        else:
            bad.append((p, why))

    # --- and now the ones a filesystem glob cannot see ---
    containers = sorted(p for p in skills_dir.rglob("*")
                        if p.suffix.lower() in CONTAINER and p.is_file())
    inspected = 0
    embedded_total = 0
    for c in containers:
        inspected += 1
        media = embedded_media(c)
        if not media:
            continue                      # a container with no images ships no images
        embedded_total += len(media)
        rel = str(c.relative_to(root))
        if rel in THIRD_PARTY_CONTAINERS:
            licensed += len(media)
            continue
        kb = sum(n for _, n in media) / 1024
        bad.append((c, f"ships {len(media)} embedded image(s) ({kb:,.0f} KB) inside the container "
                       f"— {', '.join(n for n, _ in media[:4])}"
                       f"{' ...' if len(media) > 4 else ''}; "
                       f"not named in THIRD_PARTY_CONTAINERS"))

    if not bad:
        print(f"OK: all {len(images)} loose image(s) and the {embedded_total} image(s) embedded in "
              f"{inspected} container(s) may be shipped "
              f"({ours} generated by this project, {licensed} licensed for redistribution).")
        return 0

    print(f"BUNDLED_MEDIA_UNLICENSED: {len(bad)} item(s) cannot be shipped "
          f"({len(images)} loose image(s) + {inspected} container(s) inspected).\n")
    for p, why in bad:
        print(f"  {p.relative_to(root)}")
        print(f"      {why}")
    print(
        "\nThis repository is MIT-licensed and is downloaded by every user. Shipping an image means\n"
        "granting the world the right to copy, modify and sell it — which we can only do for material\n"
        "we hold. Either:\n"
        "  * it is ours -> add its filename pattern to SELF_GENERATED in this script, naming the\n"
        "    script that renders it; or\n"
        "  * it is someone else's -> add a <name>.meta.yaml with `source`/`doi` AND a `license` that\n"
        "    permits redistribution (CC-BY, CC0, public domain); or\n"
        "  * we cannot demonstrate permission -> do not ship it. Keep it locally; a file you never\n"
        "    commit is never redistributed.\n"
        "\nFor a .pptx / .docx / .xlsx, the images are INSIDE the zip and the same three options apply\n"
        "to every one of them. If the container is licensed for redistribution, record it in\n"
        "THIRD_PARTY_CONTAINERS above with the evidence — the licence, and where it is stated. If it is\n"
        "not, the container goes. Do NOT strip its metadata and keep it: that removes the only record\n"
        "of where the images came from while still shipping them, which is worse than doing nothing.\n"
        "\nAnd if a user needs the journal's own template, they can download it themselves — the\n"
        "generator already accepts `--template /absolute/path.pptx`. Pointing at a file is not the\n"
        "same as redistributing it.\n"
        "\nA figure you may legally read is not a figure you may legally ship."
    )
    return 1 if a.strict else 0


if __name__ == "__main__":
    sys.exit(main())
