#!/usr/bin/env python3
"""render_docx.py — render markdown to Word via pandoc, with proper styling.

The renderer:
  - Shells out to pandoc (avoids hand-rolled markdown parsing bugs).
  - Uses assets/styles/lawyer-reference.docx for styling (Calibri 11 body,
    Calibri Light navy headings, page numbers, margins, blockquote indent,
    table grid).
  - Preserves bold / italic / inline code in every context (paragraphs, list
    items, table cells, headings, blockquotes).
  - Preserves multi-paragraph blockquotes as multi-paragraph.
  - Preserves [INSERT — ...] placeholders literally (smart-quote replacement
    disabled).
  - Defaults output to ./Data Act outputs/{date}_{type}.docx in
    the lawyer's current working directory; falls back to ~/Desktop/Data Act
    outputs/ if cwd is not writeable or resolves inside the skill folder.
  - Appends the short disclaimer (with FAQ version + verified-as-of date).
  - Prints absolute path AND a file:// URI on success.

Usage:
    python3 render_docx.py --template assets/templates/classification-memo.md \\
                           --deliverable-type classification-memo
    python3 render_docx.py --template <md> --out <explicit-path.docx>

Set output preference once:
    python3 render_docx.py --set-output cwd|desktop|<path>
    python3 render_docx.py --get-output

Pandoc dependency:
    macOS:   brew install pandoc
    Linux:   sudo apt-get install pandoc  (or dnf/pacman/zypper)
    Windows: https://pandoc.org/installing.html
"""
import argparse
import json
import os
import re
import shutil
import subprocess
import sys
import tempfile
from datetime import date
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
REFERENCE_DOCX = ROOT / "assets" / "styles" / "lawyer-reference.docx"
VERSIONS_FILE = ROOT / "assets" / "source" / "_versions.json"
CONFIG_FILE = ROOT / "config.json"
CHANGELOG_FILE = ROOT / "CHANGELOG.md"
DISCLAIMER_FOOTER = """**Sources verified:** Regulation (EU) 2023/2854 + European Commission Data Act FAQ v[X.Y], as of [verified_as_of date]. The Commission may have published amendments or FAQ revisions since this date. Before relying on this draft, confirm currency at [EUR-Lex Regulation 2023/2854](https://eur-lex.europa.eu/eli/reg/2023/2854) and the [European Commission Data Act FAQ](https://digital-strategy.ec.europa.eu/en/faqs/data-act-explained-frequently-asked-questions). If your copy of this skill is more than a few months old, check Lawvable for a newer release.

**Disclaimer.** This document is a starting-point draft generated by an information and drafting-assistance tool. It is not legal advice and is not a substitute for advice from a qualified lawyer admitted in the relevant jurisdiction. The European Commission Data Act FAQ is non-authoritative. This document does not address sectoral lex specialis (including, without limitation, Reg. 2018/858, MDR, DORA, NIS2, AI Act) or member-state implementing law; the lawyer must independently verify those overlays."""


def load_skill_version() -> str:
    """Read the current skill version from the top-most CHANGELOG.md heading."""
    if not CHANGELOG_FILE.exists():
        return "draft"
    m = re.search(r"^##\s*\[?(\d+\.\d+\.\d+)\]?", CHANGELOG_FILE.read_text(), re.M)
    return m.group(1) if m else "draft"


# --------------------------------------------------------------------------
# Pandoc check
# --------------------------------------------------------------------------
def check_pandoc():
    if shutil.which("pandoc") is None:
        sys.stderr.write(
            "ERROR: pandoc is not installed. The renderer requires pandoc.\n"
            "Install:\n"
            "  macOS:   brew install pandoc\n"
            "  Linux:   sudo apt-get install pandoc\n"
            "  Windows: https://pandoc.org/installing.html\n"
        )
        sys.exit(2)


# --------------------------------------------------------------------------
# Config + versions helpers
# --------------------------------------------------------------------------
def load_json(p):
    if not p.exists():
        return {}
    return json.loads(p.read_text())


def save_config(cfg):
    CONFIG_FILE.write_text(json.dumps(cfg, indent=2))


def load_versions():
    data = load_json(VERSIONS_FILE)
    return {
        "faq_version": (data.get("faq") or {}).get("version", "unknown"),
        "verified_as_of": data.get("last_check_date", "unknown"),
    }


def load_disclaimer(versions):
    block = DISCLAIMER_FOOTER
    block = block.replace("[X.Y]", versions["faq_version"])
    block = block.replace("[verified_as_of date]", versions["verified_as_of"])
    return block


# --------------------------------------------------------------------------
# Output path resolution
# --------------------------------------------------------------------------
def is_inside_skill(p: Path) -> bool:
    try:
        p.resolve().relative_to(ROOT.resolve())
        return True
    except ValueError:
        return False


def safe_filename(text: str, default: str = "deliverable") -> str:
    if not text:
        return default
    return re.sub(r"[^\w\-]+", "_", text).strip("_") or default


def determine_output_path(args, cfg) -> Path:
    if args.out:
        out = Path(args.out).expanduser().resolve()
        out.parent.mkdir(parents=True, exist_ok=True)
        return out

    today = date.today().isoformat()
    fname = f"{today}_{safe_filename(args.deliverable_type)}.docx"

    pref = (cfg.get("output_dir") or "").strip()
    cwd = Path.cwd().resolve()

    if pref == "" or pref == "cwd":
        if not is_inside_skill(cwd) and os.access(cwd, os.W_OK):
            base = cwd / "Data Act outputs"
        else:
            # Fall back to Desktop
            base = Path.home() / "Desktop" / "Data Act outputs"
    elif pref == "desktop":
        base = Path.home() / "Desktop" / "Data Act outputs"
    else:
        base = Path(pref).expanduser()

    out = base / fname
    out.parent.mkdir(parents=True, exist_ok=True)
    return out


# --------------------------------------------------------------------------
# Pandoc render
# --------------------------------------------------------------------------
PANDOC_FROM = (
    "markdown"
    "-smart"          # disable smart quotes / em-dash mangling so [INSERT — ...] survives
    "+pipe_tables"
    "+grid_tables"
    "+task_lists"
    "+raw_attribute"
    "+fenced_code_attributes"
)

PANDOC_TO = "docx"


def run_pandoc(input_md: Path, output_docx: Path, *, client: str = "") -> None:
    check_pandoc()
    cmd = [
        "pandoc",
        "-f", PANDOC_FROM,
        "-t", PANDOC_TO,
        "-o", str(output_docx),
        "--standalone",
    ]
    if REFERENCE_DOCX.exists():
        cmd.append(f"--reference-doc={REFERENCE_DOCX}")
    if client:
        cmd.extend(["--metadata", f"title={client}"])
    cmd.append(str(input_md))
    subprocess.run(cmd, check=True)


def assemble_with_disclaimer(template_path: Path) -> Path:
    """Append the short disclaimer to the template content, return temp path."""
    versions = load_versions()
    disclaimer = load_disclaimer(versions)
    body = template_path.read_text()

    skill_version = load_skill_version()
    footer_blob = (
        f"\n\n---\n\n"
        f"{disclaimer}\n\n"
        f"_Generated by EU Data Act Skill v{skill_version} · "
        f"verified against Reg. 2023/2854 + EC FAQ v{versions['faq_version']} "
        f"as of {versions['verified_as_of']}._\n"
    )
    tmp = tempfile.NamedTemporaryFile("w", suffix=".md", delete=False, encoding="utf-8")
    tmp.write(body)
    tmp.write(footer_blob)
    tmp.close()
    return Path(tmp.name)


# --------------------------------------------------------------------------
# Output prefs (--set-output / --get-output)
# --------------------------------------------------------------------------
def set_output_pref(value: str) -> None:
    cfg = load_json(CONFIG_FILE)
    cfg["output_dir"] = value
    save_config(cfg)
    print(f"output_dir = {value!r}")


def get_output_pref() -> None:
    cfg = load_json(CONFIG_FILE)
    print(f"output_dir = {cfg.get('output_dir', '(unset — defaults to cwd)')!r}")


# --------------------------------------------------------------------------
# CLI
# --------------------------------------------------------------------------
def main() -> int:
    p = argparse.ArgumentParser(
        description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter
    )
    p.add_argument("--template", help="Path to markdown template")
    p.add_argument("--out", help="Explicit output .docx path (overrides config)")
    p.add_argument("--client", default="", help="Header / matter reference shown on title row")
    p.add_argument("--deliverable-type", default="deliverable",
                   help="Short label for the file name (e.g., classification-memo)")
    p.add_argument("--set-output", metavar="VALUE",
                   help="Persist output preference: 'cwd', 'desktop', or an absolute path")
    p.add_argument("--get-output", action="store_true", help="Print current output preference")
    args = p.parse_args()

    if args.get_output:
        get_output_pref()
        return 0

    if args.set_output is not None:
        set_output_pref(args.set_output)
        return 0

    if not args.template:
        p.error("--template is required (unless --set-output / --get-output)")

    template_path = Path(args.template)
    if not template_path.exists():
        sys.stderr.write(f"Template not found: {template_path}\n")
        return 2

    cfg = load_json(CONFIG_FILE)
    output_path = determine_output_path(args, cfg)

    tmp_md = assemble_with_disclaimer(template_path)
    try:
        run_pandoc(tmp_md, output_path, client=args.client)
    finally:
        try:
            tmp_md.unlink()
        except OSError:
            pass

    abs_path = output_path.resolve()
    print(f"Wrote {abs_path}")
    print(f"Open: {abs_path.as_uri()}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
