#!/usr/bin/env Rscript
# ==============================================================================
# Batch Cohort Analysis Generator
# Generates N analysis scripts from a base template × variable combinations
#
# Usage:
#   Rscript batch_template_generator.R \
#     --template base_template.R \
#     --combinations combinations.csv \
#     --outdir batch_20260417/ \
#     --mode code_only|execute|full
#
# Combinations CSV columns:
#   id, exposure_var, exposure_label, exposure_coding,
#   outcome_var, outcome_label, outcome_coding,
#   covariates_remove (comma-separated vars to drop from default set)
# ==============================================================================

suppressPackageStartupMessages({
  library(optparse)
  library(glue)
})

# --- CLI Arguments ---
option_list <- list(
  make_option("--template", type = "character", help = "Path to base R template"),
  make_option("--combinations", type = "character", help = "CSV with variable combinations"),
  make_option("--outdir", type = "character", default = "batch_output", help = "Output directory"),
  make_option("--mode", type = "character", default = "code_only",
              help = "code_only | execute | full"),
  make_option("--parallel", type = "integer", default = 1, help = "Number of parallel workers")
)
opt <- parse_args(OptionParser(option_list = option_list))

# --- Read Inputs ---
template_code <- readLines(opt$template)
combos <- read.csv(opt$combinations, stringsAsFactors = FALSE)
cat(glue("Loaded {nrow(combos)} combinations from {opt$combinations}\n\n"))

# --- Create Output Structure ---
dir.create(file.path(opt$outdir, "scripts"), recursive = TRUE, showWarnings = FALSE)
dir.create(file.path(opt$outdir, "template"), showWarnings = FALSE)
dir.create(file.path(opt$outdir, "logs"), showWarnings = FALSE)

# Freeze template
writeLines(template_code, file.path(opt$outdir, "template", "base_template.R"))

# --- Generate Scripts ---
script_paths <- character(nrow(combos))

for (i in seq_len(nrow(combos))) {
  combo <- combos[i, ]
  script_name <- sprintf("%02d_%s_%s.R", i, combo$exposure_var, combo$outcome_var)
  script_path <- file.path(opt$outdir, "scripts", script_name)

  # Results directory for this combination
  results_dir <- file.path(opt$outdir, "results",
                           sprintf("%02d_%s_%s", i, combo$exposure_var, combo$outcome_var))
  dir.create(results_dir, recursive = TRUE, showWarnings = FALSE)

  # Replace slot variables in template
  code <- template_code
  code <- gsub("\\{\\{EXPOSURE_VAR\\}\\}", combo$exposure_var, code)
  code <- gsub("\\{\\{EXPOSURE_LABEL\\}\\}", combo$exposure_label, code)
  code <- gsub("\\{\\{EXPOSURE_CODING\\}\\}", combo$exposure_coding, code)
  code <- gsub("\\{\\{OUTCOME_VAR\\}\\}", combo$outcome_var, code)
  code <- gsub("\\{\\{OUTCOME_LABEL\\}\\}", combo$outcome_label, code)
  code <- gsub("\\{\\{OUTCOME_CODING\\}\\}", combo$outcome_coding, code)
  code <- gsub("\\{\\{RESULTS_DIR\\}\\}", results_dir, code)
  code <- gsub("\\{\\{COMBO_ID\\}\\}", sprintf("%02d", i), code)

  # Handle covariate removal (self-adjustment prevention)
  if (!is.na(combo$covariates_remove) && nchar(combo$covariates_remove) > 0) {
    remove_vars <- trimws(strsplit(combo$covariates_remove, ",")[[1]])
    remove_str <- paste0('"', remove_vars, '"', collapse = ", ")
    code <- gsub("\\{\\{COVARIATES_REMOVE\\}\\}", remove_str, code)
  } else {
    code <- gsub("\\{\\{COVARIATES_REMOVE\\}\\}", "", code)
  }

  writeLines(code, script_path)
  script_paths[i] <- script_path
  cat(glue("  Generated: {script_name}\n"))
}

# --- Generate Master Runner ---
runner_path <- file.path(opt$outdir, "scripts", "run_all.R")
runner_code <- c(
  "#!/usr/bin/env Rscript",
  "# Master runner — executes all batch scripts sequentially",
  "# Auto-generated by batch_template_generator.R",
  "",
  'cat("=== Batch Cohort Analysis ===\\n")',
  glue('cat("Combinations: {nrow(combos)}\\n")'),
  glue('cat("Started: ", format(Sys.time(), "%Y-%m-%d %H:%M:%S"), "\\n\\n")'),
  "",
  "results_log <- data.frame(",
  "  id = character(), exposure = character(), outcome = character(),",
  "  status = character(), time_sec = numeric(), error_msg = character(),",
  "  stringsAsFactors = FALSE",
  ")",
  "",
  "scripts <- c(",
  paste0('  "', script_paths, '"', collapse = ",\n"),
  ")",
  "",
  "for (i in seq_along(scripts)) {",
  "  cat(sprintf('\\n--- Running %d/%d: %s ---\\n', i, length(scripts), basename(scripts[i])))",
  "  t0 <- proc.time()['elapsed']",
  "  status <- tryCatch({",
  "    source(scripts[i], local = new.env())",
  '    "SUCCESS"',
  "  }, error = function(e) {",
  '    paste0("FAILED: ", conditionMessage(e))',
  "  })",
  "  elapsed <- round(proc.time()['elapsed'] - t0, 1)",
  "  is_ok <- startsWith(status, 'SUCCESS')",
  "  results_log <- rbind(results_log, data.frame(",
  paste0("    id = sprintf('%02d', i),"),
  "    exposure = basename(scripts[i]),",
  "    outcome = '',",
  '    status = ifelse(is_ok, "SUCCESS", "FAILED"),',
  "    time_sec = elapsed,",
  '    error_msg = ifelse(is_ok, "", status),',
  "    stringsAsFactors = FALSE",
  "  ))",
  "  cat(sprintf('  %s (%.1fs)\\n', status, elapsed))",
  "}",
  "",
  "# Save execution log",
  glue('write.csv(results_log, "{file.path(opt$outdir, "logs", "batch_execution.csv")}", row.names = FALSE)'),
  "",
  'cat("\\n=== Batch Complete ===\\n")',
  'cat(sprintf("Success: %d / %d\\n", sum(results_log$status == "SUCCESS"), nrow(results_log)))',
  'cat(sprintf("Failed:  %d / %d\\n", sum(results_log$status == "FAILED"), nrow(results_log)))'
)
writeLines(runner_code, runner_path)
cat(glue("\nMaster runner: {runner_path}\n"))

# --- Generate Summary Aggregator ---
aggregator_path <- file.path(opt$outdir, "scripts", "aggregate_results.R")
aggregator_code <- c(
  "#!/usr/bin/env Rscript",
  "# Aggregate results from all batch runs into summary matrix",
  "",
  glue('results_base <- "{file.path(opt$outdir, "results")}"'),
  "dirs <- list.dirs(results_base, recursive = FALSE)",
  "",
  "all_main <- list()",
  "all_subgroup <- list()",
  "",
  "for (d in dirs) {",
  '  main_file <- file.path(d, "main_results.csv")',
  "  if (file.exists(main_file)) {",
  "    df <- read.csv(main_file, stringsAsFactors = FALSE)",
  "    df$combo_id <- basename(d)",
  "    all_main[[length(all_main) + 1]] <- df",
  "  }",
  '  sub_file <- file.path(d, "subgroup_results.csv")',
  "  if (file.exists(sub_file)) {",
  "    df <- read.csv(sub_file, stringsAsFactors = FALSE)",
  "    df$combo_id <- basename(d)",
  "    all_subgroup[[length(all_subgroup) + 1]] <- df",
  "  }",
  "}",
  "",
  "if (length(all_main) > 0) {",
  "  summary_matrix <- do.call(rbind, all_main)",
  glue('  write.csv(summary_matrix, "{file.path(opt$outdir, "summary", "summary_matrix.csv")}", row.names = FALSE)'),
  '  cat(sprintf("Summary matrix: %d rows from %d combinations\\n", nrow(summary_matrix), length(all_main)))',
  "}",
  "",
  "if (length(all_subgroup) > 0) {",
  "  subgroup_matrix <- do.call(rbind, all_subgroup)",
  glue('  write.csv(subgroup_matrix, "{file.path(opt$outdir, "summary", "subgroup_matrix.csv")}", row.names = FALSE)'),
  '  cat(sprintf("Subgroup matrix: %d rows\\n", nrow(subgroup_matrix)))',
  "}"
)
dir.create(file.path(opt$outdir, "summary"), showWarnings = FALSE)
writeLines(aggregator_code, aggregator_path)
cat(glue("Aggregator: {aggregator_path}\n"))

# --- Execute if requested ---
if (opt$mode %in% c("execute", "full")) {
  cat("\n=== Executing batch ===\n")
  source(runner_path)

  cat("\n=== Aggregating results ===\n")
  source(aggregator_path)
}

# --- Generate README ---
readme_path <- file.path(opt$outdir, "README.md")
readme <- c(
  glue("# Batch Cohort Analysis — {Sys.Date()}"),
  "",
  glue("- **Template**: `{opt$template}`"),
  glue("- **Combinations**: {nrow(combos)}"),
  glue("- **Mode**: {opt$mode}"),
  "",
  "## Combination Matrix",
  "",
  "| # | Exposure | Outcome | Covariates Removed |",
  "|---|----------|---------|-------------------|",
  apply(combos, 1, function(row) {
    sprintf("| %s | %s | %s | %s |",
            row["id"], row["exposure_label"], row["outcome_label"],
            ifelse(is.na(row["covariates_remove"]), "—", row["covariates_remove"]))
  }),
  "",
  "## Notes",
  "",
  "- This is an **exploratory** analysis for hypothesis generation, not confirmation.",
  "- Multiple comparisons: interpret p-values with caution (Bonferroni threshold shown in summary).",
  "- Survey weights applied to all analyses.",
  glue("- Data file SHA256: [compute with `shasum -a 256 <datafile>`]"),
  ""
)
writeLines(readme, readme_path)

cat(glue("\n✅ Batch generation complete: {opt$outdir}/\n"))
cat(glue("   {nrow(combos)} scripts generated\n"))
